### ISSUE TITLE
번역 신청합니다.

### ISSUE THREAD

**Issue by kpsjh3927** [SqixOW/AIMER7_Translator#1]
https://www.dropbox.com/s/fkvf1vi03mb5u7u/Aimer7%20Routine%20Addendum.pdf?dl=0

tammas라는 사람의 aimer7 루틴 보완? 업데이트? 버전이라고 합니다. 레딧의 댓글들을 흝어보니 현 시점에선 aimer7 루틴 본판보다는 이걸로 시작하는게 더 좋다는 얘기가 많았습니다.

https://docs.google.com/spreadsheets/d/1hAzqdi-dl5_RrURx9gnFBo9-MOghurleY3eAALht5Kk/edit#gid=0 

이건 이미 알고계실지도 모르겠지만 에임 관련 가이드들을 모아놓은 문서입니다. 참고하세요. 감사합니다.

**Comment by kpsjh3927** [comment]
아 위에 올린 tammas의 루틴 링크는 이전 버전인것같네요.  https://www.dropbox.com/s/w316s768shjissf/Tammas%27%20Routine%20Addendum.pdf?dl=0 
이쪽이 최신판으로 보입니다!

**Comment by SqixOW** [comment]
대기열 등록 완료
